### ISSUE TITLE
Error when imported if a file 'error.png' isn't found in 'src/static/images

### ISSUE THREAD

**Issue by landesag** [mancontr/gitcms#1]
A bug appears when the module is imported on a different project. An error is thrown stating that there should be an image placed in src/static/images but that shouldn't be a requirement for the module to work.

`ERROR in ./node_modules/autopanel/dist/bundle.es6
    Module not found: Error: Can't resolve 'src/static/images/error.png' in '/.../sopra-web/node_modules/autopanel/dist'
     @ ./node_modules/autopanel/dist/bundle.es6 492:13-51
     @ ./src/index.js
     @ multi ./src/index.js ./node_modules/universal-scripts/client/init`

**Temp. workaround:** place an error image named error.png in the directory src/static/images of your project.

**Comment by mancontr** [comment]
I've replaced the image with an inline SVG, fixing the problem. This fix will be on the next release.
